/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artifact {
  'id' : bigint,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'publishedSlug' : string,
  'filename' : string,
  'language' : Language,
  'updatedAt' : bigint,
  'projectId' : bigint,
}
export type Category = { 'VideoGame' : null } |
  { 'TherapyCompanionBot' : null } |
  { 'LiveWebApp' : null } |
  { 'CustomAIAssistant' : null } |
  { 'AndroidMobileApp' : null } |
  { 'Other' : string } |
  { 'OfflineDesktopApp' : null };
export interface Goal { 'id' : bigint, 'text' : string, 'completed' : boolean }
export type Language = { 'CSS' : null } |
  { 'JavaScript' : null } |
  { 'HTML' : null } |
  { 'PlainText' : null } |
  { 'Markdown' : null };
export interface Milestone {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'completed' : boolean,
}
export interface Project {
  'id' : bigint,
  'status' : Status,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'goals' : Array<Goal>,
  'notes' : string,
  'category' : Category,
  'milestones' : Array<Milestone>,
}
export interface Revision {
  'id' : bigint,
  'createdAt' : bigint,
  'artifactId' : bigint,
  'instruction' : string,
  'previousContent' : string,
}
export type Status = { 'OnHold' : null } |
  { 'Archived' : null } |
  { 'Planning' : null } |
  { 'InProgress' : null } |
  { 'Deployed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGoal' : ActorMethod<[bigint, string], [] | [Project]>,
  'addMilestone' : ActorMethod<[bigint, string], [] | [Project]>,
  'addRevision' : ActorMethod<[bigint, string, string], [] | [Array<Revision>]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArtifact' : ActorMethod<[bigint, string, Language, string], Artifact>,
  'createProject' : ActorMethod<[string, Category, string], Project>,
  'deleteArtifact' : ActorMethod<[bigint], boolean>,
  'deleteGoal' : ActorMethod<[bigint, bigint], [] | [Project]>,
  'deleteMilestone' : ActorMethod<[bigint, bigint], [] | [Project]>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'getArtifact' : ActorMethod<[bigint], [] | [Artifact]>,
  'getArtifacts' : ActorMethod<[bigint], Array<Artifact>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getPublicArtifact' : ActorMethod<[string], [] | [Artifact]>,
  'getRevisions' : ActorMethod<[bigint], Array<Revision>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishArtifact' : ActorMethod<[bigint], [] | [Artifact]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleGoal' : ActorMethod<[bigint, bigint], [] | [Project]>,
  'toggleMilestone' : ActorMethod<[bigint, bigint], [] | [Project]>,
  'unpublishArtifact' : ActorMethod<[bigint], [] | [Artifact]>,
  'updateArtifact' : ActorMethod<
    [bigint, [] | [string], [] | [Language], [] | [string]],
    [] | [Artifact]
  >,
  'updateProject' : ActorMethod<
    [
      bigint,
      string,
      [] | [Category],
      [] | [Status],
      [] | [string],
      [] | [string],
    ],
    [] | [Project]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];