/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'OnHold' : IDL.Null,
  'Archived' : IDL.Null,
  'Planning' : IDL.Null,
  'InProgress' : IDL.Null,
  'Deployed' : IDL.Null,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});
export const Category = IDL.Variant({
  'VideoGame' : IDL.Null,
  'TherapyCompanionBot' : IDL.Null,
  'LiveWebApp' : IDL.Null,
  'CustomAIAssistant' : IDL.Null,
  'AndroidMobileApp' : IDL.Null,
  'Other' : IDL.Text,
  'OfflineDesktopApp' : IDL.Null,
});
export const Milestone = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'goals' : IDL.Vec(Goal),
  'notes' : IDL.Text,
  'category' : Category,
  'milestones' : IDL.Vec(Milestone),
});
export const Revision = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'artifactId' : IDL.Nat,
  'instruction' : IDL.Text,
  'previousContent' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Language = IDL.Variant({
  'CSS' : IDL.Null,
  'JavaScript' : IDL.Null,
  'HTML' : IDL.Null,
  'PlainText' : IDL.Null,
  'Markdown' : IDL.Null,
});
export const Artifact = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'publishedSlug' : IDL.Text,
  'filename' : IDL.Text,
  'language' : Language,
  'updatedAt' : IDL.Int,
  'projectId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGoal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Project)], []),
  'addMilestone' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Project)], []),
  'addRevision' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Vec(Revision))],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArtifact' : IDL.Func(
      [IDL.Nat, IDL.Text, Language, IDL.Text],
      [Artifact],
      [],
    ),
  'createProject' : IDL.Func([IDL.Text, Category, IDL.Text], [Project], []),
  'deleteArtifact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGoal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
  'deleteMilestone' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getArtifact' : IDL.Func([IDL.Nat], [IDL.Opt(Artifact)], ['query']),
  'getArtifacts' : IDL.Func([IDL.Nat], [IDL.Vec(Artifact)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getPublicArtifact' : IDL.Func([IDL.Text], [IDL.Opt(Artifact)], ['query']),
  'getRevisions' : IDL.Func([IDL.Nat], [IDL.Vec(Revision)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishArtifact' : IDL.Func([IDL.Nat], [IDL.Opt(Artifact)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleGoal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
  'toggleMilestone' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
  'unpublishArtifact' : IDL.Func([IDL.Nat], [IDL.Opt(Artifact)], []),
  'updateArtifact' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(Language), IDL.Opt(IDL.Text)],
      [IDL.Opt(Artifact)],
      [],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(Category),
        IDL.Opt(Status),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Opt(Project)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'OnHold' : IDL.Null,
    'Archived' : IDL.Null,
    'Planning' : IDL.Null,
    'InProgress' : IDL.Null,
    'Deployed' : IDL.Null,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const Category = IDL.Variant({
    'VideoGame' : IDL.Null,
    'TherapyCompanionBot' : IDL.Null,
    'LiveWebApp' : IDL.Null,
    'CustomAIAssistant' : IDL.Null,
    'AndroidMobileApp' : IDL.Null,
    'Other' : IDL.Text,
    'OfflineDesktopApp' : IDL.Null,
  });
  const Milestone = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'goals' : IDL.Vec(Goal),
    'notes' : IDL.Text,
    'category' : Category,
    'milestones' : IDL.Vec(Milestone),
  });
  const Revision = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'artifactId' : IDL.Nat,
    'instruction' : IDL.Text,
    'previousContent' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Language = IDL.Variant({
    'CSS' : IDL.Null,
    'JavaScript' : IDL.Null,
    'HTML' : IDL.Null,
    'PlainText' : IDL.Null,
    'Markdown' : IDL.Null,
  });
  const Artifact = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'publishedSlug' : IDL.Text,
    'filename' : IDL.Text,
    'language' : Language,
    'updatedAt' : IDL.Int,
    'projectId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGoal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Project)], []),
    'addMilestone' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Project)], []),
    'addRevision' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Vec(Revision))],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArtifact' : IDL.Func(
        [IDL.Nat, IDL.Text, Language, IDL.Text],
        [Artifact],
        [],
      ),
    'createProject' : IDL.Func([IDL.Text, Category, IDL.Text], [Project], []),
    'deleteArtifact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGoal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
    'deleteMilestone' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getArtifact' : IDL.Func([IDL.Nat], [IDL.Opt(Artifact)], ['query']),
    'getArtifacts' : IDL.Func([IDL.Nat], [IDL.Vec(Artifact)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getPublicArtifact' : IDL.Func([IDL.Text], [IDL.Opt(Artifact)], ['query']),
    'getRevisions' : IDL.Func([IDL.Nat], [IDL.Vec(Revision)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishArtifact' : IDL.Func([IDL.Nat], [IDL.Opt(Artifact)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleGoal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
    'toggleMilestone' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Project)], []),
    'unpublishArtifact' : IDL.Func([IDL.Nat], [IDL.Opt(Artifact)], []),
    'updateArtifact' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(Language), IDL.Opt(IDL.Text)],
        [IDL.Opt(Artifact)],
        [],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(Category),
          IDL.Opt(Status),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Opt(Project)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };