/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Goal {
    id: bigint;
    text: string;
    completed: boolean;
}
export type Category = {
    __kind__: "VideoGame";
    VideoGame: null;
} | {
    __kind__: "TherapyCompanionBot";
    TherapyCompanionBot: null;
} | {
    __kind__: "LiveWebApp";
    LiveWebApp: null;
} | {
    __kind__: "CustomAIAssistant";
    CustomAIAssistant: null;
} | {
    __kind__: "AndroidMobileApp";
    AndroidMobileApp: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "OfflineDesktopApp";
    OfflineDesktopApp: null;
};
export interface Artifact {
    id: bigint;
    content: string;
    isPublished: boolean;
    createdAt: bigint;
    publishedSlug: string;
    filename: string;
    language: Language;
    updatedAt: bigint;
    projectId: bigint;
}
export interface Project {
    id: bigint;
    status: Status;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    goals: Array<Goal>;
    notes: string;
    category: Category;
    milestones: Array<Milestone>;
}
export interface Revision {
    id: bigint;
    createdAt: bigint;
    artifactId: bigint;
    instruction: string;
    previousContent: string;
}
export interface UserProfile {
    name: string;
}
export interface Milestone {
    id: bigint;
    title: string;
    createdAt: bigint;
    completed: boolean;
}
export enum Language {
    CSS = "CSS",
    JavaScript = "JavaScript",
    HTML = "HTML",
    PlainText = "PlainText",
    Markdown = "Markdown"
}
export enum Status {
    OnHold = "OnHold",
    Archived = "Archived",
    Planning = "Planning",
    InProgress = "InProgress",
    Deployed = "Deployed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGoal(projectId: bigint, text: string): Promise<Project | null>;
    addMilestone(projectId: bigint, title: string): Promise<Project | null>;
    addRevision(artifactId: bigint, instruction: string, previousContent: string): Promise<Array<Revision> | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createArtifact(projectId: bigint, filename: string, language: Language, content: string): Promise<Artifact>;
    createProject(name: string, category: Category, description: string): Promise<Project>;
    deleteArtifact(id: bigint): Promise<boolean>;
    deleteGoal(projectId: bigint, goalId: bigint): Promise<Project | null>;
    deleteMilestone(projectId: bigint, milestoneId: bigint): Promise<Project | null>;
    deleteProject(id: bigint): Promise<boolean>;
    getArtifact(id: bigint): Promise<Artifact | null>;
    getArtifacts(projectId: bigint): Promise<Array<Artifact>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProject(id: bigint): Promise<Project | null>;
    getProjects(): Promise<Array<Project>>;
    getPublicArtifact(slug: string): Promise<Artifact | null>;
    getRevisions(artifactId: bigint): Promise<Array<Revision>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    publishArtifact(id: bigint): Promise<Artifact | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleGoal(projectId: bigint, goalId: bigint): Promise<Project | null>;
    toggleMilestone(projectId: bigint, milestoneId: bigint): Promise<Project | null>;
    unpublishArtifact(id: bigint): Promise<Artifact | null>;
    updateArtifact(id: bigint, filename: string | null, language: Language | null, content: string | null): Promise<Artifact | null>;
    updateProject(id: bigint, name: string, category: Category | null, status: Status | null, description: string | null, notes: string | null): Promise<Project | null>;
}
import type { Artifact as _Artifact, Category as _Category, Goal as _Goal, Language as _Language, Milestone as _Milestone, Project as _Project, Revision as _Revision, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGoal(arg0: bigint, arg1: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addGoal(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGoal(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMilestone(arg0: bigint, arg1: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilestone(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilestone(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRevision(arg0: bigint, arg1: string, arg2: string): Promise<Array<Revision> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addRevision(arg0, arg1, arg2);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRevision(arg0, arg1, arg2);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createArtifact(arg0: bigint, arg1: string, arg2: Language, arg3: string): Promise<Artifact> {
        if (this.processError) {
            try {
                const result = await this.actor.createArtifact(arg0, arg1, to_candid_Language_n11(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Artifact_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArtifact(arg0, arg1, to_candid_Language_n11(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Artifact_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: string, arg1: Category, arg2: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, to_candid_Category_n17(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Project_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, to_candid_Category_n17(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Project_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteArtifact(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArtifact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArtifact(arg0);
            return result;
        }
    }
    async deleteGoal(arg0: bigint, arg1: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMilestone(arg0: bigint, arg1: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMilestone(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMilestone(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getArtifact(arg0: bigint): Promise<Artifact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtifact(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtifact(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtifacts(arg0: bigint): Promise<Array<Artifact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtifacts(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtifacts(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicArtifact(arg0: string): Promise<Artifact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicArtifact(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicArtifact(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevisions(arg0: bigint): Promise<Array<Revision>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevisions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevisions(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishArtifact(arg0: bigint): Promise<Artifact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.publishArtifact(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishArtifact(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleGoal(arg0: bigint, arg1: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleGoal(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleGoal(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleMilestone(arg0: bigint, arg1: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMilestone(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMilestone(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishArtifact(arg0: bigint): Promise<Artifact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishArtifact(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishArtifact(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArtifact(arg0: bigint, arg1: string | null, arg2: Language | null, arg3: string | null): Promise<Artifact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArtifact(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArtifact(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: Category | null, arg3: Status | null, arg4: string | null, arg5: string | null): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Artifact_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Artifact): Artifact {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Artifact]): Artifact | null {
    return value.length === 0 ? null : from_candid_Artifact_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Revision>]): Array<Revision> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    isPublished: boolean;
    createdAt: bigint;
    publishedSlug: string;
    filename: string;
    language: _Language;
    updatedAt: bigint;
    projectId: bigint;
}): {
    id: bigint;
    content: string;
    isPublished: boolean;
    createdAt: bigint;
    publishedSlug: string;
    filename: string;
    language: Language;
    updatedAt: bigint;
    projectId: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        isPublished: value.isPublished,
        createdAt: value.createdAt,
        publishedSlug: value.publishedSlug,
        filename: value.filename,
        language: from_candid_Language_n15(_uploadFile, _downloadFile, value.language),
        updatedAt: value.updatedAt,
        projectId: value.projectId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    goals: Array<_Goal>;
    notes: string;
    category: _Category;
    milestones: Array<_Milestone>;
}): {
    id: bigint;
    status: Status;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    goals: Array<Goal>;
    notes: string;
    category: Category;
    milestones: Array<Milestone>;
} {
    return {
        id: value.id,
        status: from_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        goals: value.goals,
        notes: value.notes,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        milestones: value.milestones
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CSS: null;
} | {
    JavaScript: null;
} | {
    HTML: null;
} | {
    PlainText: null;
} | {
    Markdown: null;
}): Language {
    return "CSS" in value ? Language.CSS : "JavaScript" in value ? Language.JavaScript : "HTML" in value ? Language.HTML : "PlainText" in value ? Language.PlainText : "Markdown" in value ? Language.Markdown : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnHold: null;
} | {
    Archived: null;
} | {
    Planning: null;
} | {
    InProgress: null;
} | {
    Deployed: null;
}): Status {
    return "OnHold" in value ? Status.OnHold : "Archived" in value ? Status.Archived : "Planning" in value ? Status.Planning : "InProgress" in value ? Status.InProgress : "Deployed" in value ? Status.Deployed : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VideoGame: null;
} | {
    TherapyCompanionBot: null;
} | {
    LiveWebApp: null;
} | {
    CustomAIAssistant: null;
} | {
    AndroidMobileApp: null;
} | {
    Other: string;
} | {
    OfflineDesktopApp: null;
}): {
    __kind__: "VideoGame";
    VideoGame: null;
} | {
    __kind__: "TherapyCompanionBot";
    TherapyCompanionBot: null;
} | {
    __kind__: "LiveWebApp";
    LiveWebApp: null;
} | {
    __kind__: "CustomAIAssistant";
    CustomAIAssistant: null;
} | {
    __kind__: "AndroidMobileApp";
    AndroidMobileApp: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "OfflineDesktopApp";
    OfflineDesktopApp: null;
} {
    return "VideoGame" in value ? {
        __kind__: "VideoGame",
        VideoGame: value.VideoGame
    } : "TherapyCompanionBot" in value ? {
        __kind__: "TherapyCompanionBot",
        TherapyCompanionBot: value.TherapyCompanionBot
    } : "LiveWebApp" in value ? {
        __kind__: "LiveWebApp",
        LiveWebApp: value.LiveWebApp
    } : "CustomAIAssistant" in value ? {
        __kind__: "CustomAIAssistant",
        CustomAIAssistant: value.CustomAIAssistant
    } : "AndroidMobileApp" in value ? {
        __kind__: "AndroidMobileApp",
        AndroidMobileApp: value.AndroidMobileApp
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "OfflineDesktopApp" in value ? {
        __kind__: "OfflineDesktopApp",
        OfflineDesktopApp: value.OfflineDesktopApp
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Artifact>): Array<Artifact> {
    return value.map((x)=>from_candid_Artifact_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language | null): [] | [_Language] {
    return value === null ? candid_none() : candid_some(to_candid_Language_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n17(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status | null): [] | [_Status] {
    return value === null ? candid_none() : candid_some(to_candid_Status_n29(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    CSS: null;
} | {
    JavaScript: null;
} | {
    HTML: null;
} | {
    PlainText: null;
} | {
    Markdown: null;
} {
    return value == Language.CSS ? {
        CSS: null
    } : value == Language.JavaScript ? {
        JavaScript: null
    } : value == Language.HTML ? {
        HTML: null
    } : value == Language.PlainText ? {
        PlainText: null
    } : value == Language.Markdown ? {
        Markdown: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "VideoGame";
    VideoGame: null;
} | {
    __kind__: "TherapyCompanionBot";
    TherapyCompanionBot: null;
} | {
    __kind__: "LiveWebApp";
    LiveWebApp: null;
} | {
    __kind__: "CustomAIAssistant";
    CustomAIAssistant: null;
} | {
    __kind__: "AndroidMobileApp";
    AndroidMobileApp: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "OfflineDesktopApp";
    OfflineDesktopApp: null;
}): {
    VideoGame: null;
} | {
    TherapyCompanionBot: null;
} | {
    LiveWebApp: null;
} | {
    CustomAIAssistant: null;
} | {
    AndroidMobileApp: null;
} | {
    Other: string;
} | {
    OfflineDesktopApp: null;
} {
    return value.__kind__ === "VideoGame" ? {
        VideoGame: value.VideoGame
    } : value.__kind__ === "TherapyCompanionBot" ? {
        TherapyCompanionBot: value.TherapyCompanionBot
    } : value.__kind__ === "LiveWebApp" ? {
        LiveWebApp: value.LiveWebApp
    } : value.__kind__ === "CustomAIAssistant" ? {
        CustomAIAssistant: value.CustomAIAssistant
    } : value.__kind__ === "AndroidMobileApp" ? {
        AndroidMobileApp: value.AndroidMobileApp
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value.__kind__ === "OfflineDesktopApp" ? {
        OfflineDesktopApp: value.OfflineDesktopApp
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    OnHold: null;
} | {
    Archived: null;
} | {
    Planning: null;
} | {
    InProgress: null;
} | {
    Deployed: null;
} {
    return value == Status.OnHold ? {
        OnHold: null
    } : value == Status.Archived ? {
        Archived: null
    } : value == Status.Planning ? {
        Planning: null
    } : value == Status.InProgress ? {
        InProgress: null
    } : value == Status.Deployed ? {
        Deployed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
